#include"BitsEngine.h"
//running counter to be added to
unsigned long long counter = 0;
//b)
template<class Engine, std::size_t W,std::size_t Width, class UIntType>
void test(independent_bits_engine<Engine, W, UIntType>& iegine) {
	//use random number generated by iegine to create a bitset
	std::bitset<Width> bw(iegine());
	//add number of set bits to running counter
	counter += bw.count();
}

int main() {
	//a)
	std::cout << "a)\n";
	using Dengine = std::default_random_engine;
	//num of bitset with
	const unsigned int N = 30;
	//seed
	unsigned int seed = std::chrono::high_resolution_clock::now().time_since_epoch().count();
	//create one instance of bits_engine
	independent_bits_engine<Dengine, N, unsigned int> bEng(seed);
	//generate random number and display the integer and bitset
	std::cout << bEng() << ':' << bEng.BitSet() << std::endl;

	//b) run test many times
	int Ntrials = 64000;
	for (int i = 0; i < Ntrials; ++i) {
		test<Dengine, N, 2, unsigned int>(bEng);
	}
	std::cout << "counter/Total Outcomes=" << (double)counter / (double)(2.0*Ntrials) << '\n';

	//c)experiment with 8
	Ntrials = 64000;
	counter = 0;
	for (int i = 0; i < Ntrials; ++i) {
		test<Dengine, N, 8, unsigned int>(bEng);
	}
	std::cout << "counter/Total Outcomes=" << (double)counter / (double)(8.0*Ntrials) << '\n';

	//experiment with 16
	Ntrials = 64000;
	counter = 0;
	for (int i = 0; i < Ntrials; ++i) {
		test<Dengine, N, 16, unsigned int>(bEng);
	}
	std::cout << "counter/Total Outcomes=" << (double)counter / (double)(16.0*Ntrials) << '\n';

	//experiment with 64
	independent_bits_engine<std::mt19937_64, N, unsigned long long> bEng2(seed);
	Ntrials = 64000;
	counter = 0;
	for (int i = 0; i < Ntrials; ++i) {
		test<std::mt19937_64, N, 64, unsigned long long>(bEng2);
	}
	std::cout << "counter/Total Outcomes=" << (double)counter / (double)(64.0*Ntrials) << '\n';



	return 0;
}
